inventory/inventoryarc/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('items/', views.ItemListView.as_view(), name='items'),
    path('manufacturers/', views.ManufacturerListView.as_view(), name='manufacturers'),
    path('item/<int:pk>', views.ItemDetailView.as_view(), name='item-detail'),
    path('manufacturer/<int:pk>', views.ManufacturerDetailView.as_view(), name='manufacturer-detail'),
]

urlpatterns += [
    path('myitems/', views.LoanedItemsByUserListView.as_view(), name='my-borrowed'),
]

urlpatterns += [
    path('item/<uuid:pk>/renew/', views.renew_item_inventoryhead, name='renew-book-inventoryhead'),
]

urlpatterns += [
    path('manufacturer/create/', views.ManufacturerCreate.as_view(), name='manufacturer_create'),
    path('manufacturer/<int:pk>/update/', views.ManufacturerUpdate.as_view(), name='manufacturer_update'),
    path('manufacturer/<int:pk>/delete/', views.ManufacturerDelete.as_view(), name='manufacturer_delete'),
]

inventory/inventoryarc/inventoryarc/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import include
# from django.urls import path

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

inventory/inventoryarc/catalog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
#******************************************************************#
# Create your models here.
class Itemtype(models.Model):
    """Model representing item type."""
    name = models.CharField(max_length=200, help_text='Enter an item type (e.g. Electronics or mechanical)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name
#******************************************************************#
from django.urls import reverse # Used to generate URLs by reversing the URL patterns

class Item(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    manufacturer = models.ForeignKey('Manufacturer', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the item')
    #isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    itemtype = models.ManyToManyField(Itemtype, help_text='Select an item type for this item')

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this item."""
        return reverse('item-detail', args=[str(self.id)])
#******************************************************************#
import uuid # Required for unique book instances

class ItemInstance(models.Model):
    """Model representing a specific copy of an item (i.e. that can be borrowed from the inventory)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular item across whole inventory')
    item = models.ForeignKey('Item', on_delete=models.SET_NULL, null=True)
    #imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Item availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set item as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.item.title})'

    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

#******************************************************************#
class Manufacturer(models.Model):
    """Model representing an author."""
    company_name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    #date_of_birth = models.DateField(null=True, blank=True)
    #date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['company_name', 'address']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('manufacturer-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.company_name}, {self.address}'
#******************************************************************#
from django.forms import ModelForm

from catalog.models import ItemInstance

# class RenewItemModelForm(ModelForm):
#     def clean_due_back(self):
#        data = self.cleaned_data['due_back']
#
#        # Check if a date is not in the past.
#        if data < datetime.date.today():
#            raise ValidationError(_('Invalid date - renewal in past'))
#
#        # Check if a date is in the allowed range (+4 weeks from today).
#        if data > datetime.date.today() + datetime.timedelta(days=4):
#            raise ValidationError(_('Invalid date - renewal more than 4 days ahead'))
#
#        # Remember to always return the cleaned data.
#        return data
#     class Meta:
#         model = ItemInstance
#         fields = ['due_back']
#         labels = {'due_back': _('New renewal date')}
#         help_texts = {'due_back': _('Enter a date between now and 4 days (default 3).')}
#******************************************************************#

#******************************************************************#

inventory/inventoryarc/catalog/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class RenewItemForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 days (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 days ahead'))

        # Remember to always return the cleaned data.
        return data

inventory/inventoryarc/catalog/views.py
from django.shortcuts import render

# Create your views here.
from catalog.models import Item, Manufacturer, ItemInstance, Itemtype

def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_items = Item.objects.all().count()
    num_instances = ItemInstance.objects.all().count()

    # Available items (status = 'a')
    num_instances_available = ItemInstance.objects.filter(status__exact='a').count()

    # The 'all()' is implied by default.
    num_manufacturers = Manufacturer.objects.count()

    context = {
        'num_items': num_items,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_manufacturers': num_manufacturers,
    }

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_items': num_items,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_manufacturers': num_manufacturers,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

from django.views import generic

class ItemListView(generic.ListView):
    model = Item
    paginate_by = 10

class ItemDetailView(generic.DetailView):
    model = Item
    paginate_by = 10

class ManufacturerListView(generic.ListView):
    model = Manufacturer
    paginate_by = 10

class ManufacturerDetailView(generic.DetailView):
    model = Manufacturer
    paginate_by = 10

from django.contrib.auth.mixins import LoginRequiredMixin

class LoanedItemsByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing items on loan to current user."""
    model = ItemInstance
    template_name ='catalog/iteminstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return ItemInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

import datetime

from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from catalog.forms import RenewItemForm

@permission_required('catalog.can_mark_returned')
def renew_item_inventoryhead(request, pk):
    """View function for renewing a specific ItemInstance by inventoryhead."""
    item_instance = get_object_or_404(ItemInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewItemForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            item_instance.due_back = form.cleaned_data['renewal_date']
            item_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewItemForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'item_instance': item_instance,
    }

    return render(request, 'catalog/item_renew_inventoryhead.html', context)


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from catalog.models import Manufacturer

class ManufacturerCreate(CreateView):
    model = Manufacturer
    fields = '__all__'
    #initial = {'date_of_death': '05/01/2018'}

class ManufacturerUpdate(UpdateView):
    model = Manufacturer
    fields = ['company_name', 'address']#, 'date_of_birth', 'date_of_death']

class ManufacturerDelete(DeleteView):
    model = Manufacturer
    success_url = reverse_lazy('manufacturers')

inventory/inventoryarc/catalog/templates/catalog/item_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ item.title }}</h1>

  <p><strong>Manufacturer:</strong> <a href="">{{ item.manufacturer }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ item.summary }}</p>
  <!-- <p><strong>ISBN:</strong> {{ book.isbn }}</p> -->
  <!-- <p><strong>Language:</strong> {{ book.language }}</p> -->
  <p><strong>Itemtype:</strong> {% for itemtype in item.itemtype.all %} {{ itemtype }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Numbers</h4>

    {% for number in item.iteminstance_set.all %}
      <hr>
      <p class="{% if number.status == 'a' %}text-success{% elif number.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ number.get_status_display }}</p>
      {% if number.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{number.due_back}}</p>
      {% endif %}
      <!-- <p><strong>Imprint:</strong> {{copy.imprint}}</p> -->
      <p class="text-muted"><strong>Id:</strong> {{number.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

inventory/inventoryarc/catalog/templates/catalog/item_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Item List</h1>
  {% if item_list %}
  <ul>
    {% for item in item_list %}
      <li>
        <a href="{{ item.get_absolute_url }}">{{ item.title }}</a> <!--({{item.manufacturer}})-->
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no items in the inventory.</p>
  {% endif %}
{% endblock %}

inventory/inventoryarc/catalog/templates/catalog/item_renew_inventoryhead.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ item_instance.item.title }}</h1>
  <p>Borrower: {{ item_instance.borrower }}</p>
  <p{% if item_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ item_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

inventory/inventoryarc/catalog/templates/catalog/iteminstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed items</h1>

    {% if iteminstance_list %}
    <ul>

      {% for iteminst in iteminstance_list %}
      <li class="{% if iteminst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'item-detail' iteminst.item.pk %}">{{iteminst.item.title}}</a> ({{ iteminst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no items borrowed.</p>
    {% endif %}       
{% endblock %}

inventory/inventoryarc/catalog/templates/catalog/manufacturer_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Manufacturer</h1>

<p>Are you sure you want to delete the Manufacturer: {{ manufacturer }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

inventory/inventoryarc/catalog/templates/catalog/manufacturer_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Manufacturer: {{ manufacturer.company_name }}</h1>

  <p><strong>Address:</strong> <a href="">{{ manufacturer.address }}</a></p> <!-- author detail link not yet defined -->
  
{% endblock %}

inventory/inventoryarc/catalog/templates/catalog/manufacturer_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

inventory/inventoryarc/catalog/templates/catalog/manufacturer_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Manufacturer List</h1>
  {% if manufacturer_list %}
  <ul>
    {% for manufacturer in manufacturer_list %}
      <li>
        <a href="{{ manufacturer.get_absolute_url }}">{{ manufacturer.company_name }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no manufacturer in the inventory.</p>
  {% endif %}
{% endblock %}